### ISSUE TITLE
Exception when I start to write some docstrings.

### ISSUE THREAD

**Issue by cganterh** [PyCQA/pep8#454]
Hi, I'm using Atom with the linter-flake8 package and I'm getting this exception from pep8:

    Error: Traceback (most recent call last):
        File "/usr/local/bin/flake8", line 11, in sys.exit(main())
        File "/usr/local/lib/python3.5/dist-packages/flake8/main.py", line 33, in main report = flake8_style.check_files()
        File "/usr/local/lib/python3.5/dist-packages/pep8.py", line 1672, in check_files runner(path)
        File "/usr/local/lib/python3.5/dist-packages/flake8/engine.py", line 95, in input_file return fchecker.check_all(expected=expected, line_offset=line_offset)
        File "/usr/local/lib/python3.5/dist-packages/pep8.py", line 1456, in check_all self.check_logical()
        File "/usr/local/lib/python3.5/dist-packages/pep8.py", line 1328, in check_logical (start_row, start_col) = mapping[0][1]
    TypeError: 'NoneType' object is not subscriptable

This happens sometimes when I start writing a docstring such as:

    def f():
        """

If you need more information just ask. (I was unsure what to include.)  
Thanks.

**Comment by sigmavirus24** [comment]
What version of flake8 are you using?

**Comment by cganterh** [comment]
`2.4.1 (pep8: 1.5.7, pyflakes: 0.8.1, mccabe: 0.3.1) CPython 3.5.0+ on Linux`

**Comment by jamert** [comment]
Looking at stacktrace, I had the same problem (or just very, very similar) on file like this:
```
$ cat pep8_error.py
class A(object):
    """
    """
        """
```
But upgrade of pep8 from 1.5.7 to 1.6.2 solved this problem:
```
$ pep8 --version
1.5.7
$ pep8 pep8_error.py
Traceback (most recent call last):
  File "/usr/local/bin/pep8", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python2.7/site-packages/pep8.py", line 1929, in _main
    report = pep8style.check_files()
  File "/usr/local/lib/python2.7/site-packages/pep8.py", line 1672, in check_files
    runner(path)
  File "/usr/local/lib/python2.7/site-packages/pep8.py", line 1684, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/local/lib/python2.7/site-packages/pep8.py", line 1456, in check_all
    self.check_logical()
  File "/usr/local/lib/python2.7/site-packages/pep8.py", line 1328, in check_logical
    (start_row, start_col) = mapping[0][1]
TypeError: 'NoneType' object has no attribute '__getitem__'
$ // upgrading pep8
$ pep8 --version
1.6.2
$ pep8 pep8_error.py
pep8_error.py:4:9: E901 TokenError: EOF in multi-line string
```
Except this was on Mac OS X, Python 2.7.10

**Comment by rewritten** [comment]
Same problem here, with more up-to-date version:
```
2.5.1 (pep8: 1.5.7, pyflakes: 1.0.0, mccabe: 0.3.1, radon: <property object at 0x10b5dc788>)
CPython 2.7.10 on Darwin
```

**Comment by jayschwa** [comment]
I was running into this issue, but upgrading to pep8 v1.6.2 seems to have resolved it.

**Comment by sigmavirus24** [comment]
Since this was an issue with flake8 preventing a 1.6.x series version of pep8 and 1.7.0 has been released with this fix, I'm closing this. Everyone should upgrade their version of pep8/flake8.

**Comment by teodorescuserban** [comment]
+1 for updating pep8 package.

I had the same issue with pep8 1.5.7
After ```pip install --upgrade pep8``` I got pep8 1.7.0

No errors anymore.
